server.port=8083
spring.application.name=notification-service

spring.data.mongodb.uri=mongodb://delihvery:delihvery123@localhost:27017/delihvery?authSource=admin
spring.data.mongodb.database=delihvery