server.port=8081
spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://localhost:5431/delihvery
spring.datasource.username=delihvery
spring.datasource.password=delihvery123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration