server.port=8082
spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5431/delihvery
spring.datasource.username=delihvery
spring.datasource.password=delihvery123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#spring.flyway.repair-on-migrate=true
# application.properties - ONLY for local dev, never production!
#spring.flyway.clean-on-validation-error=true
#spring.flyway.clean-disabled=false

user.service.url=http://localhost:8081
notification.service.url=http://localhost:8083